try {
  throw new Error("Deu error em nada");
} catch (error) {
  console.log(error);
}
